services:
  master:
    image: postgres:17.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: elk
    volumes:
      - ${PWD}/data/pgdata-master:/var/lib/postgresql/data
      - ${PWD}/scripts/init_master.sh:/docker-entrypoint-initdb.d/init_master.sh
    networks:
      - devpops2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maxim -d elk"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  slave:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: 123
    entrypoint: /docker-entrypoint-initdb.d/init_slave.sh #запускается перед конфигурацией postgres
    ports:
      - 5434:5432
    volumes:
      - ${PWD}/data/pgdata-slave:/var/lib/postgresql/data
      - ${PWD}/scripts/init_slave.sh:/docker-entrypoint-initdb.d/init_slave.sh
    networks:
      - devpops2
    depends_on:
      master:
        condition: service_healthy

networks:
  devpops2:
    driver: bridge

# host    replication     replicator      0.0.0.0/0               md5
# pg_basebackup -h master -p 5432 -U replicator -D /data/ -Fp -Xs -R
# docker exec -it postgres-1 bash
# # create a new user
# createuser -U postgresadmin -P -c 5 --replication replicationUser
# exit


# -e POSTGRES_USER=postgresadmin `
# -e POSTGRES_PASSWORD=admin123 `
# -e POSTGRES_DB=postgresdb `
# -e PGDATA="/data" `
# -v ${PWD}/pgdata:/data `
# -v ${PWD}/config:/config `
# -p 5000:5432 `
# хуйня ебанная
# postgres:15.0 -c 'config_file=/config/postgresql.conf'