x-patroni-env: &patroni-env
  PATRONI_API_CONNECT_PORT: 8008 # patroni слушает внутри контейнера
  PATRONI_REPLICATION_USERNAME: replicator
  PATRONI_REPLICATION_PASSWORD: replpass
  PATRONI_SUPERUSER_USERNAME: postgres
  PATRONI_SUPERUSER_PASSWORD: supass
  #  POSTGRES_APP_ROLE_PASS: appass

services:
  etcd1:
    hostname: etcd1
    image: quay.io/coreos/etcd:v3.5.18
    entrypoint: /usr/local/bin/etcd
    container_name: etcd1
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"
    environment:
      - ETCD_NAME=etcd1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379 # чтобы patroni знал в какой порт обращаться

      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=${SECRET}
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      - devpops2

  etcd2:
    hostname: etcd2
    image: quay.io/coreos/etcd:v3.5.18
    entrypoint: /usr/local/bin/etcd
    container_name: etcd2
    # ports:
    #   - "2381:2379"
    #   - "2382:2380"
    environment:
      - ETCD_NAME=etcd2
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379

      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=${SECRET}
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      - devpops2

  etcd3:
    hostname: etcd3
    image: quay.io/coreos/etcd:v3.5.18
    entrypoint: /usr/local/bin/etcd
    container_name: etcd3
    # ports:
    #   - "2383:2379"
    #   - "2384:2380"
    environment:
      - ETCD_NAME=etcd3
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379

      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=${SECRET}
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      - devpops2

  patroni-1:
    container_name: patroni-1
    build: .
    hostname: patroni-1
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - test-data-1:/var/lib/postgresql/patroni/main # волумом владеет root
    environment: *patroni-env
    entrypoint: [/bin/sh, /entrypoint.sh]
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      - devpops2

  patroni-2:
    container_name: patroni-2
    build: .
    hostname: patroni-2
    entrypoint: [/bin/sh, /entrypoint.sh]
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - test-data-2:/var/lib/postgresql/patroni/main
    environment: *patroni-env
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      - devpops2

  patroni-3:
    container_name: patroni-3
    build: .
    hostname: patroni-3
    entrypoint: [/bin/sh, /entrypoint.sh]
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - test-data-3:/var/lib/postgresql/patroni/main
    environment: *patroni-env
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      - devpops2
  
  haproxy:
    image: haproxy:3.1.3-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 5432:5432
      - 5433:5433
      - 8080:8080
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    networks:
      - devpops2

networks:
  devpops2:
    driver: bridge

volumes:
  test-data-1:
  test-data-2:
  test-data-3: